<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Argentina Standard Time">
<General productName="HP Unified Functional Testing" productVer="12.02" os="Windows 8" host="EN1710257"><DocLocation><![CDATA[C:\Users\sarodriguez\Desktop\Nextech\nx\actionTest]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[actionTest]]></DName>
<Res><![CDATA[Res62]]></Res>
<RunType fmStep="True" /><DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Action rID="T3">
<AName><![CDATA[Nextech_Login]]></AName>
<Step rID="T4">
<Obj plainTxt="False" ><![CDATA[Nextech_LogIn_Screen]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[12/29/2021 - 17:07:26]]></Time>
<TimeTick>1640808446</TimeTick>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Nextech_Backup_Screen]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[12/29/2021 - 17:07:26]]></Time>
<TimeTick>1640808446</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Backup_Button.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/29/2021 - 17:07:26]]></Time>
<TimeTick>1640808446</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="10" Source="Nextech_Login" SourceLine="1" >
<Disp><![CDATA[Backup_Button.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="9" Source="Nextech_Login" SourceLine="1" >
<Disp><![CDATA[Nextech_Backup_Screen]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[LogIn_Button.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/29/2021 - 17:07:28]]></Time>
<TimeTick>1640808448</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="12" Source="Nextech_Login" SourceLine="2" >
<Disp><![CDATA[LogIn_Button.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="8" Source="Nextech_Login" SourceLine="1" >
<Disp><![CDATA[Nextech_LogIn_Screen]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Nextech_Home_Screen]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[12/29/2021 - 17:07:37]]></Time>
<TimeTick>1640808457</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Nextech_Practice_Window]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[12/29/2021 - 17:07:37]]></Time>
<TimeTick>1640808457</TimeTick>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[OK_Button.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/29/2021 - 17:07:37]]></Time>
<TimeTick>1640808457</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="16" Source="Nextech_Login" SourceLine="3" >
<Disp><![CDATA[OK_Button.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="15" Source="Nextech_Login" SourceLine="3" >
<Disp><![CDATA[Nextech_Practice_Window]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[What'sNew_Screen]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[12/29/2021 - 17:07:38]]></Time>
<TimeTick>1640808458</TimeTick>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[WhatsNew_RemindMeLater_Button.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/29/2021 - 17:07:38]]></Time>
<TimeTick>1640808458</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="19" Source="Nextech_Login" SourceLine="4" >
<Disp><![CDATA[WhatsNew_RemindMeLater_Button.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="18" Source="Nextech_Login" SourceLine="4" >
<Disp><![CDATA[What'sNew_Screen]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="14" Source="Nextech_Login" SourceLine="3" >
<Disp><![CDATA[Nextech_Home_Screen]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="12/29/2021 - 17:07:24" eTime="12/29/2021 - 17:07:38" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="3" nRep="6" >
<Disp><![CDATA[Nextech_Login Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T13">
<AName><![CDATA[SelectPatient]]></AName>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Nextech_Home_Screen]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[12/29/2021 - 17:07:38]]></Time>
<TimeTick>1640808458</TimeTick>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[PatientDropdown]]></Obj>
<Details plainTxt="False" ><![CDATA[ActiveX]]></Details>
<Time><![CDATA[12/29/2021 - 17:07:38]]></Time>
<TimeTick>1640808458</TimeTick>
<HtmlStep rID="T16">
<HTML><![CDATA[<html>
<head>
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8"/>
<base href=""/>
<link rel="stylesheet" href="Results.css"/>
</head>
<body bgcolor="#ffffff" leftmargin="20" marginwidth="20" topmargin="10" marginheight="10" vlink="#9966cc">
<table border="0" cellpadding="0" cellspacing="0" width="100%">
	<tr><td height="1" class="bg_midblue"></td></tr>
	<tr><td height="30"><span class="hl1"> Standard Output Value "NexTech DataList Control 2.0": </span><span class="DoneHigh">Done</span></td></tr>
	<tr><td height="2" class="bg_darkblue"></td></tr>
	<tr><td height="10"></td></tr>
	<tr><td><span class="text"><b>Date and Time:</b> 12/29/2021 - 17:07:38</span></td></tr>
		
	<tr><td height="15"></td></tr>
</table>
<!--Until here code from report media-->
<table border="0" cellpadding="0" cellspacing="0" width="100%" id=TABLE2><tr height="1"><td height="1" class="bg_gray_ccc"></td></tr><tr><td height="5"></td></tr></table><table>
	<tr><td height="30"><span class="hl2"> Details</span></td></tr><tr><td height="5"></td></tr>
</table>
<table border="0" cellpadding="3" cellspacing="1" width="100%" bgcolor="#666699">
	<tr>
		<td bgcolor="white">
		<table border="0" cellpadding="3" cellspacing="0" width="100%">
<tr><td  class="hl3">NexTech DataList Control 2.0 Results&nbsp;</td></tr>
<tr><th colspan=4 height=1 class="bg_darkblue"></th></tr>
<TR>
				<td height=1 class="tablehl">Property Name&nbsp;&nbsp;</td>
				<td height=1 class="tablehl">Captured Value&nbsp;&nbsp;</td>
				<td height=1 class="tablehl">Type&nbsp;&nbsp;</td>
				<td height=1 class="tablehl">Name&nbsp;&nbsp;</td>
</TR>
			<TR><th colspan=4 height=1 class="bg_gray_eee"></th></TR><tr><th colspan=4 height=1 class="bg_darkblue"></th></tr>
<TR>
				<td class="text">comboboxtext&nbsp;</td>
				<td class="text">Rodriguez_2, Santiago  (1594355564)&nbsp;</td>
				<td class="text">Repository Parameter&nbsp;</td>
				<td class="text">NexTech_DataList_Control_ComboBoxText_out1&nbsp;</td>
</TR>
			<TR><th colspan=4 height=1 class="bg_gray_eee"></th></TR>
		</table>
		</td>
	</tr>
</table>
</body></html>]]></HTML>
<TimeTick>1640808458</TimeTick>
<NodeArgs eType="Verification" icon="7" nRep="24" Source="SelectPatient" SourceLine="2" >
<Disp><![CDATA[Output "NexTech DataList Control 2.0"]]></Disp>
</NodeArgs>
</HtmlStep>
<NodeArgs eType="Context" icon="7" nRep="23" Source="SelectPatient" SourceLine="2" >
<Disp><![CDATA[PatientDropdown]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[PatientDropdown.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["Rodriguez_2, Santiago  (1594355564)"]]></Details>
<Time><![CDATA[12/29/2021 - 17:07:39]]></Time>
<TimeTick>1640808459</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="26" Source="SelectPatient" SourceLine="5" >
<Disp><![CDATA[PatientDropdown.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[PatientDropdown.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["&lt__MicReturn&gt"]]></Details>
<Time><![CDATA[12/29/2021 - 17:07:39]]></Time>
<TimeTick>1640808459</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="28" Source="SelectPatient" SourceLine="6" >
<Disp><![CDATA[PatientDropdown.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[PatientDropdown.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[285, 19]]></Details>
<Time><![CDATA[12/29/2021 - 17:07:40]]></Time>
<TimeTick>1640808460</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="30" Source="SelectPatient" SourceLine="7" >
<Disp><![CDATA[PatientDropdown.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[PatientDropdown.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["&lt__MicReturn&gt"]]></Details>
<Time><![CDATA[12/29/2021 - 17:07:40]]></Time>
<TimeTick>1640808460</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="32" Source="SelectPatient" SourceLine="8" >
<Disp><![CDATA[PatientDropdown.Type]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="22" Source="SelectPatient" SourceLine="2" >
<Disp><![CDATA[Nextech_Home_Screen]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="12/29/2021 - 17:07:38" eTime="12/29/2021 - 17:07:40" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="3" nRep="21" >
<Disp><![CDATA[SelectPatient Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T21">
<AName><![CDATA[CreateCCDA]]></AName>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Nextech_Home_Screen]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[12/29/2021 - 17:07:41]]></Time>
<TimeTick>1640808461</TimeTick>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Patients]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[12/29/2021 - 17:07:41]]></Time>
<TimeTick>1640808461</TimeTick>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Tabs.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1254, 15]]></Details>
<Time><![CDATA[12/29/2021 - 17:07:41]]></Time>
<TimeTick>1640808461</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="38" Source="CreateCCDA" SourceLine="1" >
<Disp><![CDATA[Tabs.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[History_New_Button.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/29/2021 - 17:07:42]]></Time>
<TimeTick>1640808462</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="40" Source="CreateCCDA" SourceLine="2" >
<Disp><![CDATA[History_New_Button.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="37" Source="CreateCCDA" SourceLine="1" >
<Disp><![CDATA[Patients]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="36" Source="CreateCCDA" SourceLine="1" >
<Disp><![CDATA[Nextech_Home_Screen]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Menu]]></Obj>
<Details plainTxt="False" ><![CDATA[WinMenu]]></Details>
<Time><![CDATA[12/29/2021 - 17:07:42]]></Time>
<TimeTick>1640808462</TimeTick>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Menu.Select]]></Obj>
<Details plainTxt="False" ><![CDATA[";Create Summary of Care...;"]]></Details>
<Time><![CDATA[12/29/2021 - 17:07:42]]></Time>
<TimeTick>1640808462</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="43" Source="CreateCCDA" SourceLine="3" >
<Disp><![CDATA[Menu.Select]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="42" Source="CreateCCDA" SourceLine="3" >
<Disp><![CDATA[Menu]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Nextech_Home_Screen]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[12/29/2021 - 17:07:42]]></Time>
<TimeTick>1640808462</TimeTick>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[New_Button_Dropdown.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["&lt__MicDwn&gt"]]></Details>
<Time><![CDATA[12/29/2021 - 17:07:42]]></Time>
<TimeTick>1640808462</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="46" Source="CreateCCDA" SourceLine="4" >
<Disp><![CDATA[New_Button_Dropdown.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[New_Button_Dropdown.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["&lt__MicReturn&gt"]]></Details>
<Time><![CDATA[12/29/2021 - 17:07:42]]></Time>
<TimeTick>1640808462</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="48" Source="CreateCCDA" SourceLine="5" >
<Disp><![CDATA[New_Button_Dropdown.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[SuccessCareDocumentGenerated_Window]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[12/29/2021 - 17:07:48]]></Time>
<TimeTick>1640808468</TimeTick>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[SuccessCareDocumentGenerated_OKButton.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/29/2021 - 17:07:48]]></Time>
<TimeTick>1640808468</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="51" Source="CreateCCDA" SourceLine="6" >
<Disp><![CDATA[SuccessCareDocumentGenerated_OKButton.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="50" Source="CreateCCDA" SourceLine="6" >
<Disp><![CDATA[SuccessCareDocumentGenerated_Window]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="45" Source="CreateCCDA" SourceLine="4" >
<Disp><![CDATA[Nextech_Home_Screen]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="12/29/2021 - 17:07:40" eTime="12/29/2021 - 17:07:48" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="3" nRep="34" >
<Disp><![CDATA[CreateCCDA Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T33">
<AName><![CDATA[Action7]]></AName>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Nextech_Home_Screen]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[12/29/2021 - 17:07:49]]></Time>
<TimeTick>1640808469</TimeTick>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[Patients]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[12/29/2021 - 17:07:49]]></Time>
<TimeTick>1640808469</TimeTick>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[CCDA_File]]></Obj>
<Details plainTxt="False" ><![CDATA[ActiveX]]></Details>
<Time><![CDATA[12/29/2021 - 17:07:49]]></Time>
<TimeTick>1640808469</TimeTick>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[CCDA_File_2.DblClick]]></Obj>
<Details plainTxt="False" ><![CDATA[276, 68]]></Details>
<Time><![CDATA[12/29/2021 - 17:07:49]]></Time>
<TimeTick>1640808469</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="58" Source="Action7" SourceLine="0" >
<Disp><![CDATA[CCDA_File_2.DblClick]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="57" Source="Action7" SourceLine="0" >
<Disp><![CDATA[CCDA_File]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="56" Source="Action7" SourceLine="0" >
<Disp><![CDATA[Patients]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[CCDA_XLM_Window]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[12/29/2021 - 17:08:12]]></Time>
<TimeTick>1640808492</TimeTick>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[ViewXLM_Button.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[71, 6]]></Details>
<Time><![CDATA[12/29/2021 - 17:08:12]]></Time>
<TimeTick>1640808492</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="73" status="Warning" Source="Action7" SourceLine="1" >
<Disp><![CDATA[ViewXLM_Button.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[ViewXLM_Button]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the "ViewXLM_Button" object's parent "CCDA_XLM_Window" (class Window). Verify that parent properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[12/29/2021 - 17:08:12]]></Time>
<TimeTick>1640808492</TimeTick>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[CCDA_XLM_Window]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>regexpwndtitle = XML Document<br>regexpwndclass = #32770<br>is owned window = -1<br>is child window = 0<br>]]></Details>
<Time><![CDATA[12/29/2021 - 17:08:12]]></Time>
<TimeTick>1640808492</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="75" status="Warning" nType="Parent description" Source="Action7" SourceLine="1" >
<Disp><![CDATA[CCDA_XLM_Window]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="9" nRep="74" status="Failed" nType="Run Error" Source="Action7" SourceLine="1" >
<Disp><![CDATA[ViewXLM_Button]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[12/29/2021 - 17:08:12]]></Time>
<TimeTick>1640808492</TimeTick>
<NodeArgs eType="General" icon="11" nRep="80" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="72" status="Failed" Source="Action7" SourceLine="1" >
<Disp><![CDATA[CCDA_XLM_Window]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="55" status="Failed" Source="Action7" SourceLine="0" >
<Disp><![CDATA[Nextech_Home_Screen]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="12/29/2021 - 17:07:48" eTime="12/29/2021 - 17:08:12" passed="0" failed="1" warnings="2" ></Summary>
<NodeArgs eType="StartAction" icon="3" nRep="53" status="Failed" >
<Disp><![CDATA[Action7 Summary]]></Disp>
</NodeArgs>
</Action>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[12/29/2021 - 17:08:12]]></Time>
<TimeTick>1640808492</TimeTick>
<NodeArgs eType="General" icon="12" nRep="82" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="12/29/2021 - 17:07:22" eTime="12/29/2021 - 17:08:12" passed="0" failed="1" warnings="2" stopped="True" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Test actionTest Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>