<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Argentina Standard Time">
<General productName="HP Unified Functional Testing" productVer="12.02" os="Windows 8" host="EN1710257"><DocLocation><![CDATA[C:\Users\sarodriguez\Desktop\Nextech\nx\actionTest]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[actionTest]]></DName>
<Res><![CDATA[Res51]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Nextech_Login]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Nextech_LogIn_Screen]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[12/28/2021 - 17:17:53]]></Time>
<TimeTick>1640722673</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Nextech_Backup_Screen]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[12/28/2021 - 17:17:53]]></Time>
<TimeTick>1640722673</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Backup_Button.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/28/2021 - 17:17:53]]></Time>
<TimeTick>1640722673</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="11" Source="Nextech_Login" SourceLine="1" >
<Disp><![CDATA[Backup_Button.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="10" Source="Nextech_Login" SourceLine="1" >
<Disp><![CDATA[Nextech_Backup_Screen]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[LogIn_Button.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/28/2021 - 17:17:56]]></Time>
<TimeTick>1640722676</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="13" Source="Nextech_Login" SourceLine="2" >
<Disp><![CDATA[LogIn_Button.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="9" Source="Nextech_Login" SourceLine="1" >
<Disp><![CDATA[Nextech_LogIn_Screen]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Nextech_Home_Screen]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[12/28/2021 - 17:18:11]]></Time>
<TimeTick>1640722691</TimeTick>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[ZipCodeWarning_Screen]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[12/28/2021 - 17:18:11]]></Time>
<TimeTick>1640722691</TimeTick>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[ZipCodeWarning_OK_Button.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/28/2021 - 17:18:11]]></Time>
<TimeTick>1640722691</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="17" Source="Nextech_Login" SourceLine="3" >
<Disp><![CDATA[ZipCodeWarning_OK_Button.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="16" Source="Nextech_Login" SourceLine="3" >
<Disp><![CDATA[ZipCodeWarning_Screen]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[What'sNew_Screen]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[12/28/2021 - 17:18:12]]></Time>
<TimeTick>1640722692</TimeTick>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[WhatsNew_RemindMeLater_Button.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/28/2021 - 17:18:12]]></Time>
<TimeTick>1640722692</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="20" Source="Nextech_Login" SourceLine="4" >
<Disp><![CDATA[WhatsNew_RemindMeLater_Button.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="19" Source="Nextech_Login" SourceLine="4" >
<Disp><![CDATA[What'sNew_Screen]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="15" Source="Nextech_Login" SourceLine="3" >
<Disp><![CDATA[Nextech_Home_Screen]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="12/28/2021 - 17:17:42" eTime="12/28/2021 - 17:18:12" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" >
<Disp><![CDATA[Nextech_Login Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T14">
<AName><![CDATA[SelectPatient]]></AName>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Nextech_Home_Screen]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[12/28/2021 - 17:18:13]]></Time>
<TimeTick>1640722693</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[PatientDropdown]]></Obj>
<Details plainTxt="False" ><![CDATA[ActiveX]]></Details>
<Time><![CDATA[12/28/2021 - 17:18:13]]></Time>
<TimeTick>1640722693</TimeTick>
<HtmlStep rID="T17">
<HTML><![CDATA[<html>
<head>
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8"/>
<base href=""/>
<link rel="stylesheet" href="Results.css"/>
</head>
<body bgcolor="#ffffff" leftmargin="20" marginwidth="20" topmargin="10" marginheight="10" vlink="#9966cc">
<table border="0" cellpadding="0" cellspacing="0" width="100%">
	<tr><td height="1" class="bg_midblue"></td></tr>
	<tr><td height="30"><span class="hl1"> Standard Output Value "NexTech DataList Control 2.0_2": </span><span class="DoneHigh">Done</span></td></tr>
	<tr><td height="2" class="bg_darkblue"></td></tr>
	<tr><td height="10"></td></tr>
	<tr><td><span class="text"><b>Date and Time:</b> 12/28/2021 - 17:18:13</span></td></tr>
		
	<tr><td height="15"></td></tr>
</table>
<!--Until here code from report media-->
<table border="0" cellpadding="0" cellspacing="0" width="100%" id=TABLE2><tr height="1"><td height="1" class="bg_gray_ccc"></td></tr><tr><td height="5"></td></tr></table><table>
	<tr><td height="30"><span class="hl2"> Details</span></td></tr><tr><td height="5"></td></tr>
</table>
<table border="0" cellpadding="3" cellspacing="1" width="100%" bgcolor="#666699">
	<tr>
		<td bgcolor="white">
		<table border="0" cellpadding="3" cellspacing="0" width="100%">
<tr><td  class="hl3">NexTech DataList Control 2.0_2 Results&nbsp;</td></tr>
<tr><th colspan=4 height=1 class="bg_darkblue"></th></tr>
<TR>
				<td height=1 class="tablehl">Property Name&nbsp;&nbsp;</td>
				<td height=1 class="tablehl">Captured Value&nbsp;&nbsp;</td>
				<td height=1 class="tablehl">Type&nbsp;&nbsp;</td>
				<td height=1 class="tablehl">Name&nbsp;&nbsp;</td>
</TR>
			<TR><th colspan=4 height=1 class="bg_gray_eee"></th></TR><tr><th colspan=4 height=1 class="bg_darkblue"></th></tr>
<TR>
				<td class="text">comboboxtext&nbsp;</td>
				<td class="text">Rodriguez_2, Santiago  (1594355564)&nbsp;</td>
				<td class="text">DataTable&nbsp;</td>
				<td class="text">NexTech_DataList_Control_ComboBoxText_out&nbsp;</td>
</TR>
			<TR><th colspan=4 height=1 class="bg_gray_eee"></th></TR>
		</table>
		</td>
	</tr>
</table>
</body></html>]]></HTML>
<TimeTick>1640722693</TimeTick>
<NodeArgs eType="Verification" icon="8" nRep="25" Source="SelectPatient" SourceLine="2" >
<Disp><![CDATA[Output "NexTech DataList Control 2.0_2"]]></Disp>
</NodeArgs>
</HtmlStep>
<NodeArgs eType="Context" icon="8" nRep="24" Source="SelectPatient" SourceLine="2" >
<Disp><![CDATA[PatientDropdown]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[PatientDropdown.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["Rodriguez_2, Santiago  (1594355564)"]]></Details>
<Time><![CDATA[12/28/2021 - 17:18:14]]></Time>
<TimeTick>1640722694</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="27" Source="SelectPatient" SourceLine="5" >
<Disp><![CDATA[PatientDropdown.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[PatientDropdown.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["&lt__MicReturn&gt"]]></Details>
<Time><![CDATA[12/28/2021 - 17:18:15]]></Time>
<TimeTick>1640722695</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="29" Source="SelectPatient" SourceLine="6" >
<Disp><![CDATA[PatientDropdown.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[PatientDropdown.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[285, 19]]></Details>
<Time><![CDATA[12/28/2021 - 17:18:16]]></Time>
<TimeTick>1640722696</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="31" Source="SelectPatient" SourceLine="7" >
<Disp><![CDATA[PatientDropdown.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[PatientDropdown.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["&lt__MicReturn&gt"]]></Details>
<Time><![CDATA[12/28/2021 - 17:18:16]]></Time>
<TimeTick>1640722696</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="33" Source="SelectPatient" SourceLine="8" >
<Disp><![CDATA[PatientDropdown.Type]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="23" Source="SelectPatient" SourceLine="2" >
<Disp><![CDATA[Nextech_Home_Screen]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="12/28/2021 - 17:18:12" eTime="12/28/2021 - 17:18:16" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="22" >
<Disp><![CDATA[SelectPatient Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T22">
<AName><![CDATA[Action3]]></AName>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Nextech_Home_Screen]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[12/28/2021 - 17:18:17]]></Time>
<TimeTick>1640722697</TimeTick>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Patients]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[12/28/2021 - 17:18:17]]></Time>
<TimeTick>1640722697</TimeTick>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[Tabs.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1254, 15]]></Details>
<Time><![CDATA[12/28/2021 - 17:18:17]]></Time>
<TimeTick>1640722697</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="39" Source="Action3" SourceLine="0" >
<Disp><![CDATA[Tabs.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[History_New_Button.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/28/2021 - 17:18:18]]></Time>
<TimeTick>1640722698</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="41" Source="Action3" SourceLine="1" >
<Disp><![CDATA[History_New_Button.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="38" Source="Action3" SourceLine="0" >
<Disp><![CDATA[Patients]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="37" Source="Action3" SourceLine="0" >
<Disp><![CDATA[Nextech_Home_Screen]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[NewMenu]]></Obj>
<Details plainTxt="False" ><![CDATA[WinMenu]]></Details>
<Time><![CDATA[12/28/2021 - 17:18:18]]></Time>
<TimeTick>1640722698</TimeTick>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[NewMenu.Select]]></Obj>
<Details plainTxt="False" ><![CDATA[";Create Summary of Care...;"]]></Details>
<Time><![CDATA[12/28/2021 - 17:18:18]]></Time>
<TimeTick>1640722698</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="44" Source="Action3" SourceLine="2" >
<Disp><![CDATA[NewMenu.Select]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="43" Source="Action3" SourceLine="2" >
<Disp><![CDATA[NewMenu]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Nextech_Home_Screen]]></Obj>
<Details plainTxt="False" ><![CDATA[Window]]></Details>
<Time><![CDATA[12/28/2021 - 17:18:19]]></Time>
<TimeTick>1640722699</TimeTick>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[New_Button_Dropdown.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["&lt__MicDwn&gt"]]></Details>
<Time><![CDATA[12/28/2021 - 17:18:19]]></Time>
<TimeTick>1640722699</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="47" Source="Action3" SourceLine="3" >
<Disp><![CDATA[New_Button_Dropdown.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[New_Button_Dropdown.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["&lt__MicReturn&gt"]]></Details>
<Time><![CDATA[12/28/2021 - 17:18:19]]></Time>
<TimeTick>1640722699</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="49" Source="Action3" SourceLine="4" >
<Disp><![CDATA[New_Button_Dropdown.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[SuccessCareDocumentGenerated_Window]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[12/28/2021 - 17:18:31]]></Time>
<TimeTick>1640722711</TimeTick>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[SuccessCareDocumentGenerated_OKButton.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/28/2021 - 17:18:31]]></Time>
<TimeTick>1640722711</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="65" status="Warning" Source="Action3" SourceLine="5" >
<Disp><![CDATA[SuccessCareDocumentGenerated_OKButton.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[SuccessCareDocumentGenerated_OKButton]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the "SuccessCareDocumentGenerated_OKButton" object's parent "Nextech_Home_Screen" (class Window). Verify that parent properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[12/28/2021 - 17:18:31]]></Time>
<TimeTick>1640722711</TimeTick>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[Nextech_Home_Screen]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>regexpwndtitle = Nextech<br>regexpwndclass = Afx:<br>is owned window = 0<br>is child window = 0<br>]]></Details>
<Time><![CDATA[12/28/2021 - 17:18:31]]></Time>
<TimeTick>1640722711</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="67" status="Warning" nType="Parent description" Source="Action3" SourceLine="5" >
<Disp><![CDATA[Nextech_Home_Screen]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="6" nRep="66" status="Failed" nType="Run Error" Source="Action3" SourceLine="5" >
<Disp><![CDATA[SuccessCareDocumentGenerated_OKButton]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="64" status="Failed" Source="Action3" SourceLine="5" >
<Disp><![CDATA[SuccessCareDocumentGenerated_Window]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="46" status="Failed" Source="Action3" SourceLine="3" >
<Disp><![CDATA[Nextech_Home_Screen]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the &quot;SuccessCareDocumentGenerated_OKButton&quot; object's parent &quot;Nextech_Home_Screen&quot; (class Window). Verify that parent properties match an object currently displayed in your application.<BR>Line (6): &quot;Window(&quot;Nextech_Home_Screen&quot;).Dialog(&quot;SuccessCareDocumentGenerated_Window&quot;).WinButton(&quot;SuccessCareDocumentGenerated_OKButton&quot;).Click&quot;. ]]></Details>
<Time><![CDATA[12/28/2021 - 17:18:31]]></Time>
<TimeTick>1640722711</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="68" status="Failed" Source="Action3" SourceLine="5" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[12/28/2021 - 17:18:36]]></Time>
<TimeTick>1640722716</TimeTick>
<NodeArgs eType="General" icon="12" nRep="69" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="12/28/2021 - 17:18:17" eTime="12/28/2021 - 17:18:36" passed="0" failed="2" warnings="2" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="35" status="Failed" >
<Disp><![CDATA[Action3 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Failed" >
<Disp><![CDATA[actionTest Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="12/28/2021 - 17:17:21" eTime="12/28/2021 - 17:18:36" passed="0" failed="2" warnings="2" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Test actionTest Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>